name = "share-note-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-09-01"

# Static assets (MathJax, Lucide, fonts, default styles, favicons)
[assets]
directory = "./public"
binding = "ASSETS"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "sharenotes-db"
database_id = "5f7b08fa-2011-4da8-8b04-2a8b86faf046"

# Cloudflare R2 Storage binding
[[r2_buckets]]
binding = "R2"
bucket_name = "sharenotes-storage"

# Environment variables
[vars]
BASE_WEB_URL = "https://sharenotes.guoyingwei.top"
HASH_SALT = "CHANGE_ME_IN_CF_DASHBOARD_OR_SECRETS"
ALLOW_NEW_USERS = "true"
FILENAME_LENGTH_HTML = "8"
MAXIMUM_UPLOAD_SIZE_MB = "5"
